### PR TITLE
refactor: use bucket system to handle tokens update continuously

### PR DESCRIPTION
**Pull request by warlof**
The purpose is to change the way we're updating data related to a token (ie: character info, corporation roles, etc...) to reduce load against ESI.

Currently, at a specified server tick, we queue jobs for all available tokens.
Instead, this is pairing token in dummy groups that will be used to queue new jobs at every server tick (every minute).

We keep a static update window of 60 minutes in which all tokens must be updated once.
To achieve the purpose, we split the amount of tokens across group which will be spawned dynamically. We assume a standard token Bus must be processed in 120 seconds (near to).

For performances purpose and disk health, the lastly queued bucket is stored in Redis. At every server tick, we pull either the next or the first bucket to queue jobs for its attached tokens.

Every time a token is created, deleted or changed - we ask bucket manager to update existing buckets
I wonder if update is relevant here ? We're more inquire by events which should change token distribution - which are tied to `creation` and `deletion`.

TODO :
- [x] more load testing
- [x] append migration tables and determine if console is proper package where Bucket must live in
- [x] replace logging by bus

The log bellow is showing the process based on following input :
- 804 refresh tokens
- 27 tokens as threshold
- 30 buckets

```
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90023630} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90024579} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90048331} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90174490} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90246399} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90264279} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90311399} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90389224} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90401242} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90409430} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90410260} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90414824} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90431527} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90433363} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90443211} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90496008} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90533540} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90571442} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90589658} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90604451} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90619547} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90643916} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90721386} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90735975} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90747595} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90751935} 
[2020-12-22 12:07:23] local.DEBUG: processing token from a bucket {"bucket":63,"token":90760416} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":90767384} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":90791794} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":90797687} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":90825683} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":90902919} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":90928080} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91030459} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91118314} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91151831} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91350057} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91358488} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91376015} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91436812} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91438575} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91467772} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91475240} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91484973} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91487292} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91489704} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91520900} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91533273} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91546382} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91567340} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91586371} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91586835} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":91590561} 
[2020-12-22 12:08:23] local.DEBUG: processing token from a bucket {"bucket":64,"token":2117212448} 
```

Depends on eveseat/eveapi#285
Closes eveseat/seat#731

### CODE REVIEW

**Comment by wfjsw** [comment]
Should expose bucket reseed as a Artisan Command - What would happen if I edit `refresh_tokens` table manually?

**Comment by warlof** [comment]
This is planned - also the purpose of the trait, so it avoid code duplication :)
As of edit manually the table, what kind of update are we talking about ?

However, the same result as if you edit anything outside an app :P

**Comment by wfjsw** [comment]
Once I did remove half of all tokens by hand-written SQL🤔(soft delete of course)

**Comment by warlof** [comment]
if soft delete, we don't care since tokens are already out of the the bucket :)

at worse case, we're running with unbalanced buckets - but it's to be expected if you play with the database without running business logic.

**Comment by warlof** [comment]
@wfjsw for info, I just added two commands related to bucket manager

`seat:buckets:list` which will give you list of buckets and their balance state
`seat:buckets:list ID` which will give you a bucket details
`seat:buckets:seed` which will trigger the bucket manager

image

image

**Pull request merged**
